### ISSUE TITLE
"Starting daemonization process!" but no process is started

### ISSUE THREAD

**Issue by Boza-s6** [vrmiguel/bustd#16]
After running `cargo run --release` it prints message from title, but running `ps -F -C bustd` returns empty result, ie. no `bustd` is running.

If I run it with `-n` option it exits with IO error **No such file**, so I guess it doesn't actually work. I'm on `4.15` kernel, is that the problem?

Thanks

**Comment by vrmiguel** [comment]
Hey there!

I believe the problem is that your kernel version does not have pressure stall information (PSI), which is something `bustd` requires :/

As stated in the README, PSI got added in Linux 4.20, when built with `CONFIG_PSI=y`

**Comment by vrmiguel** [comment]
Added daa0335b41662d06e176defbff4c44b21fedcb8f to supply a better error message for these cases
