### ISSUE TITLE
Security advisories for time and chrono crates used by procfs

### ISSUE THREAD

**Issue by mmstick** [vrmiguel/bustd#7]
Something to be wary of:

```
# cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 372 security advisories (from /home/mmstick/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (35 crate dependencies)
Crate:         chrono
Version:       0.4.19
Title:         Potential segfault in `localtime_r` invocations
Date:          2020-11-10
ID:            RUSTSEC-2020-0159
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:      No safe upgrade is available!
Dependency tree: 
chrono 0.4.19
└── procfs 0.11.0
    └── bustd 0.1.0

Crate:         time
Version:       0.1.44
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23
Dependency tree: 
time 0.1.44

error: 2 vulnerabilities found!
```

**Comment by vrmiguel** [comment]
I currently only use the `procfs` to test `bustd`'s own functions that read from the `proc` filesystem so these vulnerabilities _shouldn't_ be a problem in runtime

As for security, `bustd` uses unsafe is several places but mostly to interact with `libc`. I'm going to revisit all usage of unsafe and try to make sure that they are correct and add a safety comment on all of them


You mentioned considering using `bustd` on popOS earlier on Reddit, do you think there's any feature not currently implemented that would be necessary for that to happen?

**Comment by mmstick** [comment]
There's nothing that I see that we'd need that isn't already implemented. A DBus service that could send warning signals that the system is low on memory is the only thing I think would be useful to desktop applications. But that's something that could be it's own separate service unrelated to this.

**Comment by mmstick** [comment]
Feedback from QA is that the default settings may be too aggressive:

> I ran a test on a galp4 with 4GB of ram. Ran memtest 3000 and opened 20 visual studio code windows and waited until the system recovered.
> 
> Without Bustd: 44 seconds
> With Bustd: 36 seconds
> 
> Which is great, but I am concerned that with bustd if I waited another 10 seconds the OS closed all VS code windows, without a warning, and provided no reason why. Then when trying to open VS code again all 20 windows would pop up again, and while trying to close them again, Bustd closed all of the windows again.
> My feeling is that Bustd is too aggressive with closing processes.

**Comment by vrmiguel** [comment]
> Feedback from QA is that the default settings may be too aggressive:

Ohh, got it :/

Is this an impediment for using it in popOS?

The amount of process stalling time `bustd` accepts is configurable but I do think notification sending would be very useful and I'll try to implement it (soon)

**Comment by mmstick** [comment]
It is packaged in Pop!_OS, but can't be shipped by default if it's too aggressive. Is it possible to configure the rate at which processes are closed?

**Comment by marcospb19** [comment]
@mmstick, about the QA feedback you had:

> I am concerned that with bustd if I waited another 10 seconds the OS closed all VS code windows, without a warning, and provided no reason why. Then when trying to open VS code again all 20 windows would pop up again, and while trying to close them again, Bustd closed all of the windows again.

If my system is frozen, I want bustd to solve it fast, there's not much to be done in the case of Firefox, Chromium and VSCode, programs that usually reopen the last session/workspace, last time it was closed.

If VSCode is taking 5GB of my RAM, I will close all other programs before reopening it, and bustd will probably give me enough time to close it's tabs.

If that is not enough, wouldn't my machine be frozen anyways?

Also, from my experience, reopening a Firefox session that has eaten all my RAM does not immediately fill it again, most times it waits for me to switch tabs to render stuff and fill my RAM.

The only thing missing, IMHO, is a notification saying what process was killed, and how much RAM it was consuming.
